#!/bin/bash

DEVSTACK_DIR=/home/stack/devstack
DEVSTACK_INSTALL_DIR=/opt/stack

MYSQL_DB_TMPFS=false
MYSQL_DB_TMPFS_SIZE=128M

NOVA_CACHE_TMPFS=false
NOVA_CACHE_TMPFS_SIZE=24G

GLANCE_IMAGE_LIST=""
COMPUTE_NODE_LIST=""

LAB_FLAT_RANGE=172.18.124.192/26
LAB_ALLOCATION_START=172.18.124.210
LAB_ALLOCATION_END=172.18.124.224
LAB_DNS_SERVER_1=172.18.16.4
LAB_DNS_SERVER_2=172.18.16.5

#======================================
if [[ -d "$DEVSTACK_DIR" ]] ; then
    source $DEVSTACK_DIR/openrc admin admin
fi

source $SCRIPTS_DIR/functions.sh

if [[ -f "/etc/devstack-scripts/localrc" ]] ; then
    echo "Including /etc/devstack-scripts/localrc"
    source /etc/devstack-scripts/localrc
fi
