#!/bin/bash

DEVSTACK_DIR=/home/stack/devstack
DEVSTACK_INSTALL_DIR=/opt/stack
DEVSTACK_BRANCH='master'

SCREEN_LOGDIR=$DEVSTACK_INSTALL_DIR/log

MYSQL_DB_TMPFS=false
MYSQL_DB_TMPFS_SIZE=128M

NOVA_CACHE_TMPFS=false
NOVA_CACHE_TMPFS_SIZE=24G

#======================================
INSTALL_MODE=${INSTALL_MODE:-'standalone'}
if [[ -f /etc/devstack-scripts/install_mode ]] ; then
	INSTALL_MODE=$(cat /etc/devstack-scripts/install_mode)
fi


CONFIG_NAME=${CONFIG_NAME:-$(hostname)}
if [[ -f /etc/devstack-scripts/config_name ]] ; then
	CONFIG_NAME=$(cat /etc/devstack-scripts/config_name)
fi


if [[ -f "/etc/devstack-scripts/$CONFIG_NAME.devstack-scripts.localrc" ]] ; then
    _log "* Including /etc/devstack-scripts/$CONFIG_NAME.devstack-scripts.localrc"
    source /etc/devstack-scripts/$CONFIG_NAME.devstack-scripts.localrc
fi

# Set script behaviour
set -o nounset
set -o errexit
set -o xtrace
#======================================
