moduledir '/etc/puppet/modules'

# OpenStack Infra modules

mod 'jenkins',
  :git => 'https://github.com/openstack-infra/puppet-jenkins'

mod 'nodepool',
  :git => 'https://github.com/openstack-infra/puppet-nodepool'

mod 'zuul',
  :git => 'https://github.com/openstack-infra/puppet-zuul'

mod 'vcsrepo',
  :git => 'https://github.com/openstack-infra/puppet-vcsrepo'

mod 'pip',
  :git => 'https://github.com/openstack-infra/puppet-pip'

mod 'diskimage_builder',
  :git => 'https://github.com/openstack-infra/puppet-diskimage_builder'

mod 'httpd',
  :git => 'https://github.com/openstack-infra/puppet-httpd'

mod 'logrotate',
  :git => 'https://github.com/openstack-infra/puppet-logrotate'

mod 'project_config',
  :git => 'https://github.com/openstack-infra/puppet-project_config'

mod 'openstackci',
  :git => 'https://github.com/openstack-infra/puppet-openstackci'

# PuppetLabs Modules

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'mysql',
  :git => 'https://github.com/puppetlabs/puppetlabs-mysql'

mod 'firewall',
  :git => 'https://github.com/puppetlabs/puppetlabs-firewall'

mod 'ntp',
  :git => 'https://github.com/puppetlabs/puppetlabs-ntp'

