#!/bin/sh
#
# Starts murano-agent
#

AGENT_CONFIG=/etc/murano/agent.config
AGENT_LOG=/var/log/murano-agent.log

echo "M U R A N O"

check_agent() {
	# Make sure that the murano-agent progam exists
	[ -f /usr/sbin/murano-agent ] || exit 0
	[ -f "$AGENT_CONFIG" ] || exit 0
}

start() {
	echo -n "Starting murano-agent: "
	umask 077
	echo "$(/bin/date) starting /usr/sbin/murano-agent $AGENT_CONFIG $AGENT_LOG" > $AGENT_LOG
	start-stop-daemon -S -u root -q -b -x /usr/sbin/murano-agent -- $AGENT_CONIFG $AGENT_LOG
	echo "OK"
}

stop() {
	echo -n "Stopping murano-agent: "
	start-stop-daemon -K -u root -x /usr/sbin/murano-agent
	#killall murano-agent
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	check_agent
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

