includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment_filter: (?i)^(Patch Set [0-9]+:\n\n)?\s*retrigger(( (?:bug|lp)[\s#:]*(\d+))|( no bug)|( murano-ci))\s*$
        - event: comment-added
          comment_filter: recheck
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    failure-message: To re-run the job please post a comment with `retrigger murano-ci`

  - name: post
    description: This pipeline runs jobs that operate after each change is merged.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$

  - name: heartbeat
    manager: IndependentPipelineManager
    trigger:
      timer:
        - time: '2 */3 * * * *'
    failure:
      smtp:
        to: nstarodubtsev@mirantis.com, kzaitsev@mirantis.com, vryzhenkin@mirantis.com
        from: zuul@murano-ci.vm.mirantis.net
        subject: '[murano][heartbeat] Heartbeat job failed'

  - name: pulse
    manager: IndependentPipelineManager
    trigger:
      timer:
        - time: '*/15 * * * * *'
    success:
      smtp:
        to: nstarodubtsev@mirantis.com
        from: zuul@murano-ci.vm.mirantis.net
        subject: '[murano][pulse] Pulse job succeed'
    failure:
      smtp:
        to: nstarodubtsev@mirantis.com
        from: zuul@murano-ci.vm.mirantis.net
        subject: '[murano][pulse] Pulse job failed'

projects:
  - name: openstack/murano
    check:
      - gate-murano-ubuntu
    post: 
      - hook-murano-rtfd
    heartbeat:
      - heartbeat-murano-ubuntu
    pulse:
      - pulse
  - name: openstack/murano-dashboard
    check:
      - gate-murano-dashboard-ubuntu
    heartbeat:
      - heartbeat-murano-dashboard-ubuntu
  - name: openstack/murano-agent
    check:
      - gate-murano-agent-ubuntu
      #- gate-murano-agent-debian
    heartbeat:
      - heartbeat-murano-agent-ubuntu
  - name: openstack/python-muranoclient
    check:
      - gate-murano-client-ubuntu
  - name: openstack/murano-deployment
    check:
      - gate-murano-deployment

jobs:
  - name: ^.*$
    parameter-function: single_use_node
  - name: ^gate-.*$
    voting: true
  - name: ^gate-murano-agent-debian$
    voting: false
  - name: ^gate-murano-deployment$
    voting: false
