# This file is managed by puppet.
# https://git.openstack.org/cgit/openstack-infra/config

cache-root: /home/jenkins/pypimirror/cache

mirrors:
  - name: openstack
    projects:
      - git://git.openstack.org/openstack/requirements
    output: /home/jenkins/pypimirror/mirror/openstack

  - name: openstack-infra
    projects:
      - git://git.openstack.org/openstack-infra/config
    output: /home/jenkins/pypimirror/mirror/openstack-infra
